# Generated by Django 2.0.10 on 2019-01-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'verbose_name': 'Code', 'verbose_name_plural': 'Codes'},
        ),
        migrations.AddField(
            model_name='codes',
            name='answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
